[versions]

agp = "8.5.2"
kotlin = "2.0.10"
ktlint = "12.1.1"
core-ktx = "1.13.1"
appcompat = "1.7.0"
gridlayout = "1.0.0"
desugar_jdk_libs = "2.0.4"
material = "1.12.0"
dynamicanimation = "1.0.0"
work-runtime-ktx = "2.9.1"
swiperefreshlayout = "1.1.0"
constraintlayout = "2.1.4"
recyclerview = "1.3.2"
fragment-ktx = "1.8.2"
androidNavigation = "2.7.7"
androidRoom = "2.6.1"
androidLifecycle = "2.8.4"
androidTestRunner = "1.6.1"
androidTestTruth = "1.6.0"
glide = "4.16.0"
retrofit = "2.11.0"
hilt = "2.52"
hiltWork = "1.2.0"
hilt-compiler = "1.2.0"
kotlinx-coroutines = "1.8.1"
kotlinx-coroutines-test = "1.8.1"
process-phoenix = "3.0.0"
timber = "5.0.1"
circleindicator = "2.1.6"
logging-interceptor = "4.12.0"
overscroll-decor = "1.1.1"
junit = "5.10.3"
mockk = "1.13.12"
truth = "1.4.4"
core-testing = "2.2.0"

[libraries]

gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
gradle-kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-ktlint = { group = "org.jlleitschuh.gradle", name = "ktlint-gradle", version.ref = "ktlint" }

android-core = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
android-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
android-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
android-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
android-dynamicanimation = { group = "androidx.dynamicanimation", name = "dynamicanimation", version.ref = "dynamicanimation" }
android-work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime-ktx" }
android-swiperefresh = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
android-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
android-recycler = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
android-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }

android-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidNavigation" }
android-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidNavigation" }

android-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidRoom" }
android-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidRoom" }
android-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidRoom" }

android-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidLifecycle" }
android-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidLifecycle" }
android-lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "androidLifecycle" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }

hilt-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }
hilt-work-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-compiler" }

coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
phoenix = { group = "com.jakewharton", name = "process-phoenix", version.ref = "process-phoenix" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
circleIndicator = { group = "me.relex", name = "circleindicator", version.ref = "circleindicator" }
loggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }
overscrollDecor = { group = "io.github.everythingme", name = "overscroll-decor-android", version.ref = "overscroll-decor" }

# Testing
junit = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
coroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
android-test-core = { group = "androidx.arch.core", name = "core-testing", version.ref = "core-testing" }

# Android Testing
android-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidTestRunner" }
android-test-truth = { group = "androidx.test.ext", name = "truth", version.ref = "androidTestTruth" }

[bundles]

android-navigation = ["android-navigation-fragment", "android-navigation-ui"]
android-lifecycle = ["android-lifecycle-common", "android-lifecycle-runtime", "android-lifecycle-viewmodel"]
testing = ["junit", "mockk", "truth", "coroutinesTest", "android-test-core"]